# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'workerapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for workerapp
  pod 'MobileCenter', '~> 0.10.1'
  pod 'RNMobileCenterShared', '~> 0.7.0'

  

  target 'workerappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'workerapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for workerapp-tvOS

  target 'workerapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
